title: Î¼Campus 
tagline: hjkedhasjdjhoasjdljsacjldnj
author:
  name: Song-Zi Vong
  url: https://twitter.com/AbhayanVishakh

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Build Settings

paginate: 2

tags_path: /tags/
categories_path: /categories/
